//
pipeline {
      environment {
        pathBackend = "backend"
        pathYaml = "backend/yaml"
        imageName = "duhyun/springlegacy-mvc"
        dockerPath = "-f backend/yaml/Dockerfile ."
        registryCredential = 'eastshine-token'
        kubeconfig = '/home/duhyun/.kube/config'
        dockerImage = ''
    }
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('1. Docker Build') {
            steps {
                script {
                    echo "1. Docker Building..."
                    dockerImage = docker.build(imageName,"-f "+"${pathYaml}/Dockerfile .")
                }
            }
        }
        
        stage('2. Dockder Push') {
            steps {
                script {
                    echo "2. Docker Pushing..."
                    docker.withRegistry('https://registry.hub.docker.com', registryCredential) {
                            dockerImage.push("latest")
                    }
                }
            }
        }
        stage('3. K8s Deploy') {
            steps {
                script {
                    echo "3. K8s Deploy..."
                    sh "/usr/local/bin/kubectl --kubeconfig=${kubeconfig} delete -f ${pathYaml}/deploy-springmvc.yaml -n duhyun"
                    sh "/usr/local/bin/kubectl --kubeconfig=${kubeconfig} apply -f ${pathYaml}/deploy-springmvc.yaml -n duhyun"
                }
            }
        }
        stage('4. K8s Service') {
            steps {
                script {
                    echo "4. K8s Service..."
                    sh "/usr/local/bin/kubectl --kubeconfig=${kubeconfig} delete -f ${pathYaml}/service-springmvc.yaml -n duhyun"
                    sh "/usr/local/bin/kubectl --kubeconfig=${kubeconfig} apply -f ${pathYaml}/service-springmvc.yaml -n duhyun"
                }
            }
        }
        stage('5. K8s Port-Foward') {
            steps {
                script {
                    echo "5. K8s Port-Foward..."
                    sh "/usr/local/bin/kubectl --address 0.0.0.0 service/springmvc -n duhyun 8888:80"
                }
            }
        }
    }
}
