//
pipeline {
      environment {
        pathBackend = "backend"
        pathYaml = "backend/yaml"
        imageName = "duhyun/springlegacy-mvc"
        registryCredential = 'eastshine-token'
        kubeconfig = '/home/duhyun/.kube/config'
        dockerImage = ''
        namespace = "covi"
    }
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('1. Docker Build') {
            steps {
                script {
                    echo "1. Docker Building..."
                    dockerImage = docker.build(imageName,"-f "+"${pathYaml}/Dockerfile .")
                }
            }
        }
        
        stage('2. Dockder Push') {
            steps {
                script {
                    echo "2. Docker Pushing..."
                    docker.withRegistry('https://registry.hub.docker.com', registryCredential) {
                            dockerImage.push("latest")
                    }
                }
            }
        }
        stage('3. K8s Deploy') {
            steps {
                script {
                    echo "3. K8s Deploy..."
                    //sh "/usr/local/bin/kubectl --kubeconfig=${kubeconfig} delete -f ${pathYaml}/deploy-springmvc.yaml -n ${namespace}"
                    sh "/usr/local/bin/kubectl --kubeconfig=${kubeconfig} apply -f ${pathYaml}/deploy-springmvc.yaml -n ${namespace}"
                }
            }
        }
    }
}
